W9D5/solution/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  root to: redirect('/cats')
end

W9D5/solution/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord

  # freeze renders constants immutable
  STATUS_STATES = %w(APPROVED DENIED PENDING).freeze

  after_initialize :assign_pending_status

  # N.B. Remember, Rails 5 automatically validates the presence of
  # belongs_to associations, so we can leave the validation of cat and
  # user out here.
  validates :end_date, :start_date, :status, presence: true
  validates :status, inclusion: STATUS_STATES
  validate :start_must_come_before_end
  validate :does_not_overlap_approved_request

  belongs_to :cat
  belongs_to :user

  def approve!
    raise 'not pending' unless self.status == 'PENDING'
    transaction do
      self.status = 'APPROVED'
      self.save!

      # when we approve this request, we reject all other overlapping
      # requests for this cat.
      overlapping_pending_requests.each do |req|
        req.update!(status: 'DENIED')
      end
    end
  end

  def approved?
    self.status == 'APPROVED'
  end

  def denied?
    self.status == 'DENIED'
  end

  def deny!
    self.status = 'DENIED'
    self.save!
  end

  def pending?
    self.status == 'PENDING'
  end

  private

  def assign_pending_status
    self.status ||= 'PENDING'
  end

  def overlapping_requests
    # ======================================
    #
    # Ranges can overlap in several ways:
    #
    #   |-----|       |-----|     |---|
    #       |-----|   |-----|   |-------|
    #     (2x)                    (2x)
    #
    # ======================================
    #
    # However, it is easier to think of the
    # two cases where they do not overlap:
    #
    #    [Case 1]
    #
    #        A              B
    #    |-------|      |-------|
    #    A(s)    A(e)   B(s)    B(e)
    #
    # The start point of B comes after the
    # end point of A. Thus: B(s) > A(e)
    #
    #
    #    [Case 2]
    #
    #        B              A
    #    |-------|      |-------|
    #    B(s)    B(e)   A(s)    A(e)
    #
    # The start point of A comes after the
    # end point of B. Thus: A(s) > B(e)
    #
    # ======================================
    #
    # Taking those two cases, we can say
    # there's no overlap when:
    #
    #   B(s) > A(e) || A(s) > B(e)
    #
    # ======================================
    #
    # We can negate this to get all cases
    # where there must be overlap:
    #
    #   !( B(s) > A(e) || A(s) > B(e) )
    #
    # Personally, I find this most clear.
    #
    # In order for overlap to occur, the
    # other range cannot be entirely before
    # it or entirely after it.
    #
    # ======================================
    #
    # You could distribute the negation:
    #
    #   !( B(s) > A(e) ) && !( A(s) > B(e) )
    #
    # And take it even further, making it
    # shorter, but perhaps less intuitive:
    #
    #   B(s) <= A(e) && A(s) <= B(e)
    #
    # ======================================

    # We want:
    # 1. A different request
    # 2. That is for the same cat.
    # 3. That overlaps.

    CatRentalRequest
      .where.not(id: self.id)
      .where(cat_id: cat_id)
      .where.not('start_date > :end_date OR end_date < :start_date',
                 start_date: start_date, end_date: end_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where('status = \'APPROVED\'')
  end

  def overlapping_pending_requests
    overlapping_requests.where('status = \'PENDING\'')
  end

  def does_not_overlap_approved_request
    # A denied request doesn't need to be checked. A pending request
    # should be checked; users shouldn't be able to make requests for
    # periods during which a cat has already been spoken for.
    return if self.denied?

    unless overlapping_approved_requests.empty?
      errors[:base] <<
        'Request conflicts with existing approved request'
    end
  end

  def start_must_come_before_end
    errors[:start_date] << 'must specify a start date' unless start_date
    errors[:end_date] << 'must specify an end date' unless end_date
    errors[:start_date] << 'must come before end date' if start_date > end_date
  end
end

W9D5/solution/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :require_user!, only: %i(approve deny)
  before_action :require_cat_ownership!, only: %i(approve deny)

  def approve
    current_cat_rental_request.approve!
    redirect_to cat_url(current_cat)
  end

  def create
    @rental_request = CatRentalRequest.new(cat_rental_request_params)
    @rental_request.user_id = current_user.id
    if @rental_request.save
      redirect_to cat_url(@rental_request.cat)
    else
      flash.now[:errors] = @rental_request.errors.full_messages
      render :new
    end
  end

  def deny
    current_cat_rental_request.deny!
    redirect_to cat_url(current_cat)
  end

  def new
    @rental_request = CatRentalRequest.new(cat_id: params[:cat_id])
  end

  private

  def current_cat_rental_request
    @rental_request ||=
      CatRentalRequest.includes(:cat).find(params[:id])
  end

  def current_cat
    current_cat_rental_request.cat
  end

  def require_cat_ownership!
    return if current_user.owns_cat?(current_cat)
    redirect_to cat_url(current_cat)
  end

  def cat_rental_request_params
    params.require(:cat_rental_request)
      .permit(:cat_id, :end_date, :start_date, :status)
  end
end

W9D5/solution/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

W9D5/solution/app/views/cat_rental_requests/new.html.erb
<section class="page"><div class="centered-box">
  <h1>Create Rental Request</h1>

  <%= render "shared/errors" %>

  <form action="<%= cat_rental_requests_url %>" method="post">
    <% auth_token %>
    <label for="cat_rental_request_cat_id">Cat</label>
    <select name="cat_rental_request[cat_id]"
            id="cat_rental_request_cat_id">
      <option></option>
      <% Cat.all.each do |cat| %>
        <% selected = @rental_request.cat_id == cat.id %>
        <option <%= selected ? "selected" : "" %>
                value="<%= cat.id %>">
          <%= cat.name %>
        </option>
      <% end %>
    </select>
    <br>

    <label for="cat_rental_request_start_date">Start Date</label>
    <input
      type="date"
      name="cat_rental_request[start_date]"
      value="<%= @rental_request.start_date %>"
      id="cat_rental_request_start_date">
    <br>

    <label for="cat_rental_request_end_date">End Date</label>
    <input
      type="date"
      name="cat_rental_request[end_date]"
      value="<%= @rental_request.end_date %>"
      id="cat_rental_request_end_date">
    <br>

    <input type="submit">
  </form>
</div></section>
<% content_for :footer do %>
  <p>In contrast with this purely quantitative difference, which is not  an essential difference, "good" and "bad"would express an absolute  difference; but this is not in place here. Whether taken in one way or  another,action is equally carried on; there is a process of displaying  and expressing an individuality, and for thatreason it is all good: it  would, properly speaking, be impossible to say what "bad" is to be  here. What wouldbe called a bad work is the individual life of a  certain specific nature, which is therein realized. It would onlybe  degraded into a bad work by a reflective comparison, which, however, is  quite empty and futile, since thisgoes beyond the essential meaning  and nature of work (which is a self−expression of individuality, and  thenseeks to find and demand from it heaven knows what else. - G.W.F. Hegel, The Phenomenology of Mind</p>
<% end %>