W10D1/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:new, :create, :destroy, :show]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:index]
end

W10D1/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  year       :integer          not null
#  live       :boolean          default(FALSE), not null
#  band_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :name, :year, :live, presence: true
  validates :year, numericality: { greater_than: 1888}
  validates :band_id, inclusion: { in: Band.all.map(&:id) } # I'w worried about this becoming a very slow chunk of code
  belongs_to :band
end

W10D1/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums
end

W10D1/music_app/app/models/testmodel.rb
class Testmodel < ApplicationRecord
end

W10D1/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
require 'bcrypt'

class User < ApplicationRecord
  include BCrypt
  before_validation :ensure_session_token
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { in: 6..20 }, allow_nil: true

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil unless user && user.is_password?(password)
    user
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(new_pass)
    @password = new_pass
    self.password_digest = Password.create(@password)
  end

  def is_password?(test_pass)
    bcrypt_pass = Password.new(self.password_digest) # Turns password_digest back into bcrypt object
    bcrypt_pass.is_password?(test_pass)
  end
end

W10D1/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @bands = Band.all
    @album = Album.new
    render :new
  end

  def create
    @bands = Band.all
    @album = Album.new(album_params)
    if @album.save
      flash[:success] = "Album successfully created!"
      redirect_to album_url(@album.id)
    else
      flash[:errors] = @album.errors.full_messages
      if album_params[:band].nil?
        redirect_to new_album_url
      else
        redirect_to new_band_album_url(album_params[:band_id])
      end
    end
  end

  def edit
    @bands = Band.all
    @album = Album.find_by(id: params[:id])
    render :new
  end

  def show
    @album = Album.find_by(id: params[:id])
    if @album
      render :show
    else
      flash[:errors] = "Album not found"
      redirect_to :index
    end
  end

  def update
  end

  def destroy
  end

  private

  def album_params
    params.require(:album).permit(:name, :year, :live, :band_id)
  end
end

W10D1/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user 
  helper_method :logged_in? 

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def require_user!
    redirect_to new_session_url unless current_user
  end
end

W10D1/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      flash[:success] = "Band successfully created!"
      redirect_to band_url(@band.id)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to :new
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :new
  end

  def show
    @band = Band.find_by(id: params[:id])
    if @band
      render :show
    else
      flash[:errors] = "Band not found"
      redirect_to :index
    end
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band && @band.update(band_params)
      flash[:success] = "Band information successfully updated!"
      redirect_to band_url(@band.id)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to :edit
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    if @band.nil?
        flash[:errors] = "Band not found"
    end
    if @band && @band.destroy
      flash[:success] = "Band successfully removed from database!"
      redirect_to :index #perhaps add a confirmation page in the future
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to :index
    end
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

W10D1/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new 
    render :new
  end
  
  def create
    @user = User.find_by_credentials(params[:email], params[:password])

    if @user
      login_user!(@user)
      redirect_to user_url
    else
      flash.now[:errors] = "Wrong email/password combo"
      render :new, status: 401
    end
  end

  def destroy
    @user = User.find_by(session_token: session[:session_token])

    user.reset_session_token!
    session[:session_token] = nil
    redirect_to user_url
  end
end

W10D1/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :create
  end

  def show
    @user = User.find_by(session_token: session[:session_token])
    if @user
      render :show
    else
      flash[:error] = "Please sign in before attempting to view that page"
      redirect_to session_new, status: 401 # sign in should go here when I have it
    end
  end
  
  def create
    raise 'no user params given' if params[:user].nil?
    @user = User.new(email: user_params[:email])
    @user.password = user_params[:password]
    if @user.save
      login_user!(@user)
      flash[:success] = "Account successfully created!"
      redirect_to user_url(@user.id) #maybe
    else
      flash[:error] = @user.errors.full_messages
      render :new
    end

  rescue 
    redirect_to new_user_url
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W10D1/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W10D1/music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    <<-HTML.html_safe
      <input
        type="hidden"
        name="authenticity_token"
        value="#{form_authenticity_token}"
      />
    HTML
  end
end

W10D1/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W10D1/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W10D1/music_app/app/helpers/user_helper.rb
module UserHelper
end

W10D1/music_app/app/views/albums/create.html.erb
<% content_for :h1 do %>Add a new album<% end %>
<div style="display: flex; flex-direction: column;">
  <%= render 'shared/errors' %>
  <br>
  <br>
  <form action="<%= bands_url %>" method="post" style="display: flex; flex-direction: column; margin-left: 20px;">
    <%= auth_token %>
    <label for="band_name">Band name:</label>
    <button class="button dropdown" type="button" data-toggle="dropdown">
      <input
      type="text"
      name="album[band]"
      id="band_name"
      value="<%= @band.name %>"
      style="margin-bottom: 10px;"
      >
      <br>
    <input type="submit" value="Add Band" style="color: #1b1d20; background-color: #7b8187; border-radius: 5px; height: 40px; border: 0px;">
  </form>
</div>

W10D1/music_app/app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

W10D1/music_app/app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

W10D1/music_app/app/views/albums/new.html.erb
<% content_for :h1 do %>Add a new album<% end %>
<div style="display: flex; flex-direction: column;">
  <%= render 'shared/errors' %>
  <br>
  <br>
  <form action="<%= '/albums' %>" method="post" style="display: flex; flex-direction: column; margin-left: 20px;">
    <%= auth_token %>
    <section>
      <label for="album_name">Album name:</label>
      <input
        type="text"
        name="album[name]"
        id="album_name"
        value="<%= @album.name %>"
        style="margin-bottom: 10px;"
      >
      <br>
      <label for="album_band">Band name:</label>
      <select
        type="text"
        name="album[band_id]"
        id="album_band"
        value="<%= @album.band ? @album.band.id : nil %>"
        style="margin-bottom: 10px;"
      >
        <option value="">--Please select a band--</option>
        <% @bands.each do |band| %>

          <option value="<%= band.id %>"><%= band.name %></option>
        <% end %>
      </select>
      <br>

      <label for="album_year">Album year:</label>
      <input type="number" name="album[year]" id="album_year" value="<%= @album.year %>" min="1888" max="<%= 5 + Time.now.year %>">
      <br>


      <div id="boolean_radio" display="inline">
        <label for="boolean_radio">Is it a live album?</label>
        <input type="radio" name="album[live]" id="false" value="No" <%= "checked" if @album.nil? || !@album.live %>>
        <label for="false">No</label>
        <input type="radio" name="album[live]" id="true" value="Yes" <%= "checked" if @album.live %>>
        <label for="false">Yes</label>
      </div>
    </section>

    <br>
    <input type="submit" value="Add Album" style="color: #1b1d20; background-color: #7b8187; border-radius: 5px; height: 40px; border: 0px;">
  </form>
</div>

W10D1/music_app/app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

W10D1/music_app/app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>

W10D1/music_app/app/views/bands/index.html.erb
<% content_for :h1 do %>Bands<% end %>
<section class="band-index" style="margin-left: 20px;">
  <% @bands.each do |band| %>
    <div class="band-index-item" style="height: 50px; width: 50px;">
      <a href= "<%= band_url(band) %>"><%= band.name %></a>
    </div>
  <% end %>
</section>

W10D1/music_app/app/views/bands/new.html.erb
<% content_for :h1 do %>Add a new band<% end %>
<div style="display: flex; flex-direction: column;">
  <%= render 'shared/errors' %>
  <br>
  <br>
  <form action="<%= bands_url %>" method="post" style="display: flex; flex-direction: column; margin-left: 20px;">
    <%= auth_token %>
    <!--<input type="hidden" name= "authenticity_token" value="<% form_authenticity_token %>"/>-->
    <label for="band_name">Band name:</label>
    <input
      type="text"
      name="band[name]"
      id="band_name"
      value="<%= @band.name %>"
      style="margin-bottom: 10px;"
      >
      <br>
    <input type="submit" value="Add Band" style="color: #1b1d20; background-color: #7b8187; border-radius: 5px; height: 40px; border: 0px;">
  </form>
</div>

W10D1/music_app/app/views/bands/show.html.erb
<% content_for :h1 do %><%= @band.name %><% end %>
<div class="all_album_squares" style="margin-left: 20px;">
  <% @band.albums.each do |album| %>
    <div class="album-square" style="height: 100px; width: 100px;">
      <caption><%=album.name%></caption>
    </div>
  <% end %>
</div>

W10D1/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% title = ((yield :h1).empty? ? "Bee's Music App" : "Bee's Music App: #{ yield :h1}") %>
    <title><%= title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="box-sizing: border-box; margin: 0;">
    <header class="header" role="banner" style="background-color: #1b1d20; display: flex; justify-content: space-between; align-items: center; flex-wrap: nowrap; width: 100%">
      <a href="<%= bands_url %>" style="text-decoration: none">
      <h1 style="font-family: monospace; color: #b0b9c2; padding-left: 15px;">Universially Aesthetic Music</h1>
      </a>
      <!--<h1><a href="<%= %>">Musics</a></h1>-->
      <div style="padding-right: 10px; display: flex; justify-content: space-around; box-sizing: border-box; height: fill; border: 0px;">
      <% if current_user.nil? %>
        <a href="<%= new_session_url %>" style="justify-content: flex-end;">
          <button class="login" type="button" style="color: #1b1d20; background-color: #7b8187; border-radius: 5px; height: 40px; border: 0px;">
            Sign In
          </button>
        </a>
        <a href="<%= new_user_url %>" style="padding-left: 10px;">
          <button class="sign_up" type="button" style="color: #1b1d20; background-color: #7b8187; border-radius: 5px; height: 40px; border: 0px;">
            Sign up
          </button>
        </a>
      <% else %>
        <div style="color: #b0b9c2; display:flex; align-items: center;">
          <%= current_user.email %>
          <form action="<%= session_url %>" method="post" style="padding-left: 10px;">
            <%= auth_token %>
            <input type="hidden" name="_method" value="delete">
            <input type="submit" value="Logout">
          </form>
        </div>
      <% end %>
      </div>
    </header>

    <h1 style="display: flex; align-direction: column; margin-left: 25px">
      <%= "#{yield :h1}:" %>
    </h1>
    <h2>
      <%= render 'shared/errors' %>
    </h2>
    <main style="display: flex; align-direction: column; margin-left: 25px">
      <%= yield %>
    </main>
  </body>
</html>

W10D1/music_app/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>